# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy SQL project

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore=
    - name: Publish SQL project
          run: |
            SqlPackage /Action:Publish /SourceFile:fabric_workshop_source_control_sql/bin/Debug/fabric_workshop_source_control_sql.dacpac /TargetConnectionString:${{ secrets.SQL_CONNECTION_STRING }}
